### ISSUE TITLE
Visit confirmation email - usability improvement (3d)

### ISSUE THREAD

**Issue by uveybe** [Visitame/Design#1]
Once the user book a property, we are sending an email with a  calendar.ics as an attachment. 

We should include links to make easier the appointment in the user calendar.
Also, we should include a link to the map and a link to the property, so the user could find all the info in the same place.

Example:
<img width="473" alt="captura de pantalla 2018-10-02 a las 18 04 38" src="https://user-images.githubusercontent.com/22731532/46361915-276e2700-c66f-11e8-93a8-ab3fdf82e638.png">

In this first iteration, we are not going to change the email design or structure, so this new info will be added to the current structure (maybe after the description?) 

And we could also update the text formatting. We have to edit the copies because maybe its too mucha info, but if you have any idea to make it clearer in any way, please let me know!

The complete email:
[mail - Visita confirmada.pdf](https://github.com/Visitame/bot-client/files/2449937/mail.-.Visita.confirmada.pdf)

**Comment by jimenacatalina** [comment]
Listo
![confirmacion cita](https://user-images.githubusercontent.com/43912803/46631512-ea5ed480-cb47-11e8-8fa0-5d76bfc78541.png)

**Comment by jimenacatalina** [comment]
https://drive.google.com/open?id=1AraqdhlYJSoDrhZ8HYsKPA2WuozbrwFD

<blockquote><img src="https://lh5.googleusercontent.com/E99BsTXVPAogmdxZwSxTojuS8uHtJNJRoN0Jwyzh-JTTPMW0gwM1sP64UgA=w1200-h630-p" width="48" align="right"><div>Google Docs</div><div><strong><a href="https://drive.google.com/file/d/1AraqdhlYJSoDrhZ8HYsKPA2WuozbrwFD/view?usp=drive_open&usp=embed_facebook">Confirmación cita.png</a></strong></div></blockquote>
