### ISSUE TITLE
Aceptar cookies y politica de privacidad con configuración

### ISSUE THREAD

**Issue by uveybe** [Visitame/Design#10]
A petición de los abogados, tenemos que incluir la política de cookies y su aceptación.

Está toda la info en este documento: https://docs.google.com/document/d/1KheRXN9aUard0iSoeoB2AzWTAMjOLIyc4YH20SJQcn0/edit?usp=sharing

En el punto 2 está lo que los abogados nos han pedido.
En el punto 3, tienes algunos comentarios para diseño.

**Comment by jimenacatalina** [comment]
Antes de pasar las pantallas a desktop quisiera revisar con vosotros la propuesta:

**Aviso de cookies**
Con texto simplificado respecto al que plantean los abogados, que es un turrón. Básicamente decimos lo mismo así que no debería haber problema. El aviso aparece en la cabecera y hasta que se acepta empuja todo el contenido hacia abajo.
![0 cookies](https://user-images.githubusercontent.com/43912803/48616062-d1d9a980-e992-11e8-9d2d-0db1dd5d6cf9.png)

**Configuración de cookies**
Con lenguaje cercano y mostrando sólo las cookies que se pueden configurar (las obligatorias no tienen sentido en la configuración). Estarían todas en "ON" por defecto. No he visto que otras webs metan aquí la tabla de cookies específicas, me parece una burrada.
![17 configuracion cookies](https://user-images.githubusercontent.com/43912803/48616097-e74ed380-e992-11e8-95f3-f445760fcbc3.png)

**Términos de uso**
Todo el texto legal unificado en términos de uso, con anchors a política de cookies y política de privacidad. Porque al final cuando navegas una web lo estás aceptando todo junto. Desde el aviso de cookies enlazaríais al anchor de cookies, y en los formularios al anchor de política de privacidad.
![18 terminos de uso](https://user-images.githubusercontent.com/43912803/48616254-562c2c80-e993-11e8-9033-35f2377c5403.png)

Por cierto, tenéis mal la política de privacidad en Visitame.app, porque ahora mismo es una política de cookies y en absoluto son lo mismo. La política de privacidad debería referirse a los datos personales que recogéis en los formularios de "Prueba la demo"

**Comment by jimenacatalina** [comment]
Por cierto, si además pudieran redactarse en "humano" y no en "legañol" sería la bomba.
Como hace Pinterest:
https://policy.pinterest.com/es/privacy-policy
https://policy.pinterest.com/es/cookies


<blockquote><img src="https://policy.pinterest.com/sub/meta/artboard_horizontal.jpg" width="48" align="right"><div>Pinterest Policy</div><div><strong><a href="https://policy.pinterest.com/es/privacy-policy">Política de privacidad</a></strong></div></blockquote>
<blockquote><img src="https://policy.pinterest.com/sub/meta/artboard_horizontal.jpg" width="48" align="right"><div>Pinterest Policy</div><div><strong><a href="https://policy.pinterest.com/es/cookies">Cookies</a></strong></div></blockquote>

**Comment by uveybe** [comment]
Muchas gracias!! Como te comentaba, vamos a pasárselo a legal para intentar simplificarlo y resolver dudas. En cuanto a la redacción te confirmo ya que va a ser imposible a corto, han pasado bastante tiempo gestionándolo (aunque totalmente de acuerdo, también lo hace muy bien Spotahome y es de nuestro mismo sector). Punto a mejorar en el futuro, gracias!

te digo algo la semana que viene ;)

**Comment by jimenacatalina** [comment]
En el Drive:
https://drive.google.com/open?id=1qUh3PROM7zjlOwaEvbptsRAJIMYPRQYe
https://drive.google.com/open?id=1oxtAZk0Q9q5ss1OtF0UeX0oAFcRM2e4H
https://drive.google.com/open?id=1bW_13cfJpmDLei_o0hHyyoBV5NlFzTop

<blockquote><div><strong><a href="https://drive.google.com/open?id=1qUh3PROM7zjlOwaEvbptsRAJIMYPRQYe">Meet Google Drive – One place for all your files</a></strong></div><div>Google Drive is a free way to keep your files backed up and easy to reach from any phone, tablet, or computer. Start with 15GB of Google storage – free.</div></blockquote>
<blockquote><div><strong><a href="https://drive.google.com/open?id=1oxtAZk0Q9q5ss1OtF0UeX0oAFcRM2e4H">Meet Google Drive – One place for all your files</a></strong></div><div>Google Drive is a free way to keep your files backed up and easy to reach from any phone, tablet, or computer. Start with 15GB of Google storage – free.</div></blockquote>
<blockquote><div><strong><a href="https://drive.google.com/open?id=1bW_13cfJpmDLei_o0hHyyoBV5NlFzTop">Meet Google Drive – One place for all your files</a></strong></div><div>Google Drive is a free way to keep your files backed up and easy to reach from any phone, tablet, or computer. Start with 15GB of Google storage – free.</div></blockquote>

**Comment by uveybe** [comment]
Después de verlo con el abogado y revisarlo internamente se queda así:

- vamos a tener solo 1 url de cookies y otra url de términos que irán enlazados desde donde se quiera (bot y landing Ringo). Así que revisemos la navegación para que cuadre en ambos contextos y no unifiquemos los dos documentos en una única url. 
- irán bajo Ringo
- ¿puedes poner algo en español, tipo Aceptar en vez de ON/Off en la página de cookies? de lo demás todo ok
- Sobre el mensaje de cookies: vamos a quitar el botón de configurar, pero se alarga la frase: Usamos cookies para analizar el uso de nuestros servicios. Si continuas navegando, consideramos que aceptas su uso. Para más información, consulta nuestra Política de cookies. ¿Queda muy largo?

Si tienes dudas para la versión desktop o de algún otro tema, comentamos, gracias!

**Comment by jimenacatalina** [comment]
Mobile:
https://drive.google.com/open?id=1qUh3PROM7zjlOwaEvbptsRAJIMYPRQYe
https://drive.google.com/open?id=1Ya7vq9oUoXZPTsEQ885PP5fknqVi7upw
https://drive.google.com/open?id=1bW_13cfJpmDLei_o0hHyyoBV5NlFzTop

Desktop:
https://drive.google.com/open?id=1TgreP0Z_gio3CqZEQm68u7zsrz_iSoae
https://drive.google.com/open?id=1No-xm7uvmL2wxaboCvvgQf5gPmXLIFkg


<blockquote><div><strong><a href="https://drive.google.com/open?id=1qUh3PROM7zjlOwaEvbptsRAJIMYPRQYe">Meet Google Drive – One place for all your files</a></strong></div><div>Google Drive is a free way to keep your files backed up and easy to reach from any phone, tablet, or computer. Start with 15GB of Google storage – free.</div></blockquote>
<blockquote><img src="https://lh4.googleusercontent.com/B3bl533qEhICcCmmdcvAFcp4G6XBRD5aZwyEyxqpPvaNSHTz86NJ1PblJVk=w1200-h630-p" width="48" align="right"><div>Google Docs</div><div><strong><a href="https://drive.google.com/file/d/1Ya7vq9oUoXZPTsEQ885PP5fknqVi7upw/view?usp=drive_open&usp=embed_facebook">17 Política Cookies.png</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://drive.google.com/open?id=1bW_13cfJpmDLei_o0hHyyoBV5NlFzTop">Meet Google Drive – One place for all your files</a></strong></div><div>Google Drive is a free way to keep your files backed up and easy to reach from any phone, tablet, or computer. Start with 15GB of Google storage – free.</div></blockquote>
<blockquote><div><strong><a href="https://drive.google.com/open?id=1TgreP0Z_gio3CqZEQm68u7zsrz_iSoae">Meet Google Drive – One place for all your files</a></strong></div><div>Google Drive is a free way to keep your files backed up and easy to reach from any phone, tablet, or computer. Start with 15GB of Google storage – free.</div></blockquote>
<blockquote><div><strong><a href="https://drive.google.com/open?id=1No-xm7uvmL2wxaboCvvgQf5gPmXLIFkg">Meet Google Drive – One place for all your files</a></strong></div><div>Google Drive is a free way to keep your files backed up and easy to reach from any phone, tablet, or computer. Start with 15GB of Google storage – free.</div></blockquote>
