### ISSUE TITLE
El usuario ha superado el tiempo de la visita

### ISSUE THREAD

**Issue by uveybe** [Visitame/Design#12]
Queremos hacer una pantalla para después de este paso:
<img width="274" alt="captura de pantalla 2018-12-07 a las 14 06 42" src="https://user-images.githubusercontent.com/22731532/49649409-5c10ad00-fa29-11e8-9831-76cf30952061.png">

Es, decir, el usuario ha pasado el límite de tiempo determinado para su visita y empezamos a contar en positivo, es decir el tiempo que se ha excedido en la visita. Ahora mismo el contador simplemente para. En la primera versión pondremos un mensaje, pero creo que deberíamos hacer algo más adhoc para que el usuario esté informado. Y sin pasarse, porque de momento puede haber falsos positivos y queremos seguir siendo friendly. vamos a presuponer que hay buena fe por parte del usuario.

Entonces, estaba pensando en poner una pantalla entera totalmente diferente:
- con un contador en positivo que te calcule el tiempo que llevas de "más"
- con el botón de abrir la puerta "Acabar la visita y salir"
- con un mensaje que te diga que tienes que salir habiendo cerrado la puerta y revisado las luces. Y que si ya has salido y es un error, llames por teléfono a ayuda.

Igual podríamos poner además un enlace a las condiciones que el usuario ha aceptado en la parte inferior de la página a modo de recordatorio en el footer o algo similar. 

¡Cómo lo ves? Comentamos el lunes?

**Comment by jimenacatalina** [comment]
¿Con "el botón de abrir la puerta" te refieres al que ya está de "Acabar visita y salir"?

**Comment by uveybe** [comment]
Uy, sí sorry

**Comment by jimenacatalina** [comment]
Versión actual
https://drive.google.com/open?id=1KwGWLZHpsHANErEukNoNWhcQZEXItm-X
![durante - tiempo superado](https://user-images.githubusercontent.com/43912803/49939751-f9625a00-fedd-11e8-85e7-2a60669d7211.png)

Futura versión
https://drive.google.com/open?id=1M4CrjP7da94cmcdt0BDSiNS8LGU_T_5v

![4 durante - tiempo superado](https://user-images.githubusercontent.com/43912803/49939789-11d27480-fede-11e8-884c-3f8e8e05efa3.png)

![5 fin visita](https://user-images.githubusercontent.com/43912803/49939795-172fbf00-fede-11e8-8a7d-734003a185e1.png)



<blockquote><div><strong><a href="https://drive.google.com/open?id=1KwGWLZHpsHANErEukNoNWhcQZEXItm-X">Meet Google Drive – One place for all your files</a></strong></div><div>Google Drive is a free way to keep your files backed up and easy to reach from any phone, tablet, or computer. Start with 15GB of Google storage – free.</div></blockquote>
<blockquote><div><strong><a href="https://drive.google.com/open?id=1M4CrjP7da94cmcdt0BDSiNS8LGU_T_5v">Meet Google Drive – One place for all your files</a></strong></div><div>Google Drive is a free way to keep your files backed up and easy to reach from any phone, tablet, or computer. Start with 15GB of Google storage – free.</div></blockquote>
