### ISSUE TITLE
Inicio de admin con 2 tipos de login

### ISSUE THREAD

**Issue by uveybe** [Visitame/Design#13]
Necesitamos adaptar la página de inicio del Admin de clientes para 2 logins: el actual, con correo de google y el nuevo, que se usará el mobile.

El documento explicativo en detalle es este por si le quieres echar un vistazo: https://docs.google.com/document/d/14bbuIWmVMuSYQt4RsrsEDoYNj2qeU42bBIX25dcfe9I/edit?usp=sharing

En resumen la idea es:
- hacer una cabecera, con marca Visitame (en algun momento se podrá modificar). 
- un acceso dividido para loguearse (Que no registrarse) via correo o teléfono
- responsive
- pequeño footer abajo para que podamos enlazar a ayuda o algún teléfono de contacto en caso de problema

La cabecera y el footer deberán poder usarse con cualquier componente y, por ejemplo este, y deberá poder identificarse facilmente si se está haciendo login en el bot o en el admin. 

<img width="699" alt="captura de pantalla 2019-01-10 a las 10 57 08" src="https://user-images.githubusercontent.com/22731532/51122982-650c4f80-181b-11e9-8878-a0b0e298d888.png">

Y pondremos un acceso desde la web de visitame.app pero seguramente sea un acceso temporal

**Comment by jimenacatalina** [comment]
https://drive.google.com/open?id=1mx07YqVGLj7FYutBS71ykAqiQAAXIiVz

![1 login](https://user-images.githubusercontent.com/43912803/51468159-8e266600-1d6e-11e9-9a98-cf426407ff50.png)
![2 login error](https://user-images.githubusercontent.com/43912803/51468160-8ebefc80-1d6e-11e9-99f9-95eeb9ac32e4.png)

Archivo Sketch:
https://drive.google.com/open?id=1WZtHpYuBRL1H1__bF7XvrLGjV9IXnC7f

<blockquote><div><strong><a href="https://drive.google.com/open?id=1mx07YqVGLj7FYutBS71ykAqiQAAXIiVz">Visitame - Admin - Google Drive</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://drive.google.com/open?id=1WZtHpYuBRL1H1__bF7XvrLGjV9IXnC7f">Meet Google Drive – One place for all your files</a></strong></div><div>Google Drive is a free way to keep your files backed up and easy to reach from any phone, tablet, or computer. Start with 15GB of Google storage – free.</div></blockquote>
