### ISSUE TITLE
Mejora del datepicker: medias horas y multiplataforma

### ISSUE THREAD

**Issue by uveybe** [Visitame/Design#14]
## Problema a resolver
- los usuarios desktop e iOS tienen problemas para seleccionar las horas disponibles
- el horario es amplio, de 9 a 7, y se va a incorporar la posibilidad de reservar en punto y a medias , por ejemplo 09:00 y 09:30 

## Posible solución
- se podría mirar la opción de incorporar al bot o de continuar en modal. Lo importante es que sea multidispositivo

**Comment by jimenacatalina** [comment]
**Pantalla de Bienvenida**

- El bot se presenta
- En otro globo, para facilitar la comprensión de la info, se ofrecen las horas de los próximos días (las primeras de la mañana y las más habituales de la tarde ¿a partir de las 18:00 que es la hora de salir del trabajo? -> contrastar con datos cuando haya usuarios)
- Los días pueden navegarse en horizontal, si una hora no está disponible simplemente no aparece.
- El enlace de "Ver más horas" abre modal

![1 hola](https://user-images.githubusercontent.com/43912803/53334386-ed8d0e00-38f8-11e9-99d9-4b0c9e59452a.png)

**Selección de hora en bot**

- La hora seleccionada queda marcada y las demás en "disabled". No mostramos botón de "confirmar" la reserva para mantener la agilidad de la experiencia del bot.
- Aparece el globo de usuario con la fecha y hora
- El bot confirma y ofrece las opciones de Cambiar reserva (volvería a salir el globo con las fechas) o Cancelar visita (en rojo de "danger action", cancelar requeriría confirmación de "¿Estás seguro blablabla?" tal y como lo estéis haciendo ahora)

![2 elige fecha](https://user-images.githubusercontent.com/43912803/53334511-5d02fd80-38f9-11e9-84ca-78dcb2566b15.png)

**Selección de hora en modal**

Si el usuario hace clic en "Ver más horas":
- Se abre modal con todas las horas disponibles
- Los días se navegan en horizontal, las horas en vertical
- Seleccionar una hora no deshabilita las demás. En este caso sí pedimos "confirmación" que cierra la modal y vuelve al bot con los mismos mensajes del caso anterior

![3 ver mas horas](https://user-images.githubusercontent.com/43912803/53334676-c6830c00-38f9-11e9-9875-dc683eee6928.png)

![4 ver mas horas - hora seleccionada](https://user-images.githubusercontent.com/43912803/53334681-c97dfc80-38f9-11e9-8fa1-12c14874d350.png)

**Comment by uveybe** [comment]
Nos mola mucho! todavía no tenemos el cambio de horario así que genial que lo hayas incluido ya.

Lo hemos revisado el calendario y tenemos algún feedback, te lo paso por escrito y si quieres comentamos cuando quieras:

Horarios:
- creemos que es mejor poner hora de inicio y hora fin. De "10 a 10:50" o similar.  Así indicamos longitud de la visita, que es un dato que todavía no estamos dando

Opciones de navegación:
- Es difícil saber en qué día estás, así que preferiríamos que se viera solo *un día* en vez de 3. ¿cómo lo ves? También se han comentado otras opciones, como destacar más la navegación de las tabs o que se pregunte primero el horario preferido (mañana mediodía o tarde). Esta opción también sería viable.
En cuanto al modal, entiendo que habrá que adaptarlo también.

Lo dicho, cuando quieras comentamos

**Comment by jimenacatalina** [comment]
Os hago una prueba rápida para que podáis evaluar pero no lo veo.

> creemos que es mejor poner hora de inicio y hora fin. De "10 a 10:50" o similar.  Así indicamos longitud de la visita, que es un dato que todavía no estamos dando

Aumenta la carga cognitiva del usuario al tener que procesar dos horas para cada botón en lugar de uno. Además que si una cita es a las 9 y la siguiente a las 9:30 ya es evidente que como mucho va a durar media hora. Creo que hay otros momentos más efectivos para comunicar la duración de la visita, como el mail de confirmación o la propia confirmación del bot.

> preferiríamos que se viera solo _un día_ en vez de 3. ¿cómo lo ves?

Es poco probable que el usuario tenga un hueco para la visita justo el día que le muestras (que es el posterior al actual). Le obligas a navegar entre días sí o sí.

> que se pregunte primero el horario preferido (mañana mediodía o tarde)

Reduce mucho la agilidad del bot, y tampoco entiendo en qué podría ayudar a saber en qué día estás.

![1 hola v2](https://user-images.githubusercontent.com/43912803/53746231-0b321880-3ea1-11e9-8f8e-0ac9e7eda74d.png)

![4 ver mas horas - hora seleccionada v2](https://user-images.githubusercontent.com/43912803/53746232-0b321880-3ea1-11e9-83ba-7a9b5e10fe27.png)

**Comment by jimenacatalina** [comment]
Opción con 1 día y horas en 2 columnas

![1 Hola](https://user-images.githubusercontent.com/43912803/54180808-d6bfed00-449c-11e9-9776-49ff9dee7e7b.png)

![2 Elige fecha](https://user-images.githubusercontent.com/43912803/54180809-d6bfed00-449c-11e9-8c4f-c8140c9d0534.png)

![3 Ver más horas](https://user-images.githubusercontent.com/43912803/54180810-d7588380-449c-11e9-87cf-0c826ab8ce90.png)

![4 Ver más horas - Hora seleccionada v2](https://user-images.githubusercontent.com/43912803/54180811-d7588380-449c-11e9-9d1e-2a8559a6599e.png)

**Comment by jimenacatalina** [comment]
Ya están las nuevas pantallas en
https://drive.google.com/open?id=1DsZeYLxYZsBNqy_0wZrrHNM2OHgogMu4

<blockquote><div><strong><a href="https://drive.google.com/open?id=1DsZeYLxYZsBNqy_0wZrrHNM2OHgogMu4">Mobile - Google Drive</a></strong></div></blockquote>
