### ISSUE TITLE
Cartel para la puerta + teléfono

### ISSUE THREAD

**Issue by uveybe** [Visitame/Design#16]
Carlos nos pide que cambiemos el diseño del cartel de la entrada, con el objetivo de que se vea mucho el teléfono ya que los usuarios se ponen nerviosos.

El actual cartel, formato "carta" incluso destacando el teléfono (hemos hecho pruebas) aún más se le hace insuficiente y con demasiado texto
![img_20190305_100559](https://user-images.githubusercontent.com/22731532/53798096-d6bd6b80-3f37-11e9-9318-9fe21aa69315.jpg)

Dice que funcionaba mejor entre los usuarios incluso el formato antiguo, dividido en 2 zonas claramente diferenciadas.
![20190305_101336](https://user-images.githubusercontent.com/22731532/53798157-f2287680-3f37-11e9-948b-5c94a256dd64.jpg)

De momento, es el único cartel que va a ir en los inmuebles, así que podemos tocar el diseño y hacer un cartel diferente. 

¿Podrías hacer una versión alternativa con el texto parecido al actual, pero con dos zonas diferencias, una para el teléfono? Además, de momento el teléfono lo vamos a atender nosotros.

Gracias!

**Comment by jimenacatalina** [comment]
https://drive.google.com/open?id=1eB7T7mWeM2Nvl9S_prX_jXjAJB8ZPeq4

![image](https://user-images.githubusercontent.com/43912803/53881716-a3044380-4014-11e9-99f3-a22019104a21.png)


<blockquote><img src="https://lh6.googleusercontent.com/ChaFZFHEwxdy2wbFoHetAjw0_t53al2bne44MAgOGU4EewvPh9STznO3ggg=w1200-h630-p" width="48" align="right"><div>Google Docs</div><div><strong><a href="https://drive.google.com/file/d/1eB7T7mWeM2Nvl9S_prX_jXjAJB8ZPeq4/view?usp=drive_open&usp=embed_facebook">Salida Telefono.pdf</a></strong></div></blockquote>
