### ISSUE TITLE
Verification funnel error messages

### ISSUE THREAD

**Issue by nobuti** [Visitame/Design#2]
In some point along the verification funnel (saving the signup, sending the credit card details...), we catch errors but we need to inform the user about the error. I'm not talking about a validation error on a field, but the error returned by the api as a result of an operating, usually saving data.

**Comment by nobuti** [comment]
A bit more context. This is how we show errors now:

![screenshot from 2018-10-11 12-29-18](https://user-images.githubusercontent.com/1366843/46798153-7001a080-cd51-11e8-9baa-13ba2c026020.png)

**Comment by jimenacatalina** [comment]
![1 login error](https://user-images.githubusercontent.com/43912803/47382247-1cecfd80-d702-11e8-8297-92683223c4b8.png)

https://drive.google.com/open?id=1Y2igPJJUcaIxLfipI9Cqft2_0GfimUpR

<blockquote><img src="https://lh5.googleusercontent.com/llafNSpgPXhgFQdjO57TnHpsLTS2udEeHz743r9tv-IwVmH936qLbA5NUxU=w1200-h630-p" width="48" align="right"><div>Google Docs</div><div><strong><a href="https://drive.google.com/file/d/1Y2igPJJUcaIxLfipI9Cqft2_0GfimUpR/view?usp=drive_open&usp=embed_facebook">1 Login Error.png</a></strong></div></blockquote>

**Comment by jimenacatalina** [comment]
"contacta con soporte" debería ir enlazado, porque no hay ninguna manera de contactar con ellos. Pero es que no sé si de verdad tenéis soporte :D
