### ISSUE TITLE
Piloto de carteles informativos en Edgar Neville

### ISSUE THREAD

**Issue by uveybe** [Visitame/Design#3]
Vamos a hacer un piloto de incluir información física en Edgar Neville.
La idea es imprimirlo en papel con más grosor del habitual y pegarlo en cartón  pluma.

Te adjunto el ppt con la info del inmuebles, las fotos y los textos del piloto. Si quieres editarlos no hay problema.
He contado solo con titulo, descripción y firma genérica. También debería incluir logo.

https://docs.google.com/presentation/d/1K_hUFATy-ovz8vAxTTWDT9DRU3Jkrh9k3wFAAPPehto/edit?usp=sharing 

gracias!

**Comment by jimenacatalina** [comment]
Necesito que lo compartas a mi dirección de gmail

**Comment by jimenacatalina** [comment]
Aquí están https://drive.google.com/open?id=16OiNlOPc560Y_ouHwOTHKaXSFax_jsN6

<blockquote><div><strong><a href="https://drive.google.com/open?id=16OiNlOPc560Y_ouHwOTHKaXSFax_jsN6">Print - Google Drive</a></strong></div></blockquote>

**Comment by uveybe** [comment]
Hola,

Necesitamos un par de cosas:
- ¿En las puertas que no se pueden abrir, podrías añadir algún X o stop en rojo? ¿y corregir la errata de Compresión?
- ¿Podrías subir el archivo original al drive? Por si acaso hacemos cambios de texto. 

gracias

**Comment by jimenacatalina** [comment]
El cartel corregido
https://drive.google.com/open?id=1SVZYdGg5b3guxGzIV0QaictM9uB512f-

El archivo original con todos los carteles
https://drive.google.com/open?id=1kFXqIKw_GwYEMJoIWTVOuyQsIFuh0ZHe

<blockquote><img src="https://lh5.googleusercontent.com/HatNkca7etrbQuPNrfYZP-Sg0tUIlRlC6jH0LZsX8g-3u_ZqsV1ixKv3zQk=w1200-h630-p" width="48" align="right"><div>Google Docs</div><div><strong><a href="https://drive.google.com/file/d/1SVZYdGg5b3guxGzIV0QaictM9uB512f-/view?usp=drive_open&usp=embed_facebook">Espacio no visitable.pdf</a></strong></div></blockquote>
<blockquote><img src="https://ssl.gstatic.com/docs/doclist/images/icon_14_generic_favicon.ico" width="48" align="right"><div>Google Docs</div><div><strong><a href="https://drive.google.com/file/d/1kFXqIKw_GwYEMJoIWTVOuyQsIFuh0ZHe/view?usp=drive_open&usp=embed_facebook">Carteles visita.sketch</a></strong></div></blockquote>
