### ISSUE TITLE
Durante la visita: actualizar el acceso a la info del inmueble y reportar incidencia

### ISSUE THREAD

**Issue by uveybe** [Visitame/Design#4]
Una vez que el usuario entra en el inmueble aparecen una serie de pantallas informativas con esta estructura (ilustración, texto y botón de acción)
<img width="272" alt="captura de pantalla 2018-10-16 a las 12 54 05" src="https://user-images.githubusercontent.com/22731532/47011653-bcc6ec00-d142-11e8-90f4-33e52b8d110d.png">
<img width="273" alt="captura de pantalla 2018-10-16 a las 12 53 38" src="https://user-images.githubusercontent.com/22731532/47011654-bcc6ec00-d142-11e8-97be-c8adbc7f30c4.png">

El tema es que una vez que entras, si pulsas en "entendido" aparece una pantalla diferente, con un botón diferenciado para terminar la visita, con un acceso preferente a los contenidos del inmueble, que en el momento de la visita son poco útiles.

**El problema a resolver**
Lo que queremos es que el usuario sepa mientras está en la visita cómo terminar la sesión, como acceder a la ayuda, como acceder a la información del piso ampliada y sobre todo, cómo reportar una incidencia que encuentre en el piso sin que ello suponga un impedimento a la visita. porque además va a tener responsabilidades si hay algún desperfecto

<img width="276" alt="captura de pantalla 2018-10-16 a las 12 40 58" src="https://user-images.githubusercontent.com/22731532/47015358-07e5fc80-d14d-11e8-9e33-9a83cfa0d251.png">

**Propuesta de solución**

Lo que había pensado era:
- modificar el texto de Entendido por "Empezar" o "siguiente"
- que unificáramos la estructura y que el botón de cerrar sesión estuviera abajo, como en las pantallas anteriores
- que hubiera una navegación lateral para acceder a la info del piso y que esa info abriera la ficha del piso
- que incluyéramos una navegación lateral (igual parecida a la del registro?) para informar de cómo reportar incidencias. En esa nueva página se incluiría dos modos de reportar: ¿llámanos por telefono? y un botón de ¿quieres reportar algo del piso? mándanos un aviso. Este aviso tendría de título una serie de opciones predefinidas como subject, un campo libre y la posibilidad de adjuntar una foto del estado del inmueble. 

Comentamos cuando tengas un rato? Gracias

**Comment by jimenacatalina** [comment]
Pantallas
https://drive.google.com/open?id=1M4CrjP7da94cmcdt0BDSiNS8LGU_T_5v

Sketch
https://drive.google.com/open?id=1X5l0bkk9QT76BHDao5PLK4a61yy094nI

Lo del tiempo sería solo en caso de que vayáis a cobrar si te pasas del tiempo de visita. Si no lo vais a hacer se podría quitar para no agobiar.


<blockquote><div><strong><a href="https://drive.google.com/open?id=12nsn-9P5GaHhAOjXnytBYqInAJzI8p6C">Meet Google Drive – One place for all your files</a></strong></div><div>Google Drive is a free way to keep your files backed up and easy to reach from any phone, tablet, or computer. Start with 15GB of Google storage – free.</div></blockquote>
<blockquote><img src="https://ssl.gstatic.com/docs/doclist/images/icon_14_generic_favicon.ico" width="48" align="right"><div>Google Docs</div><div><strong><a href="https://drive.google.com/file/d/1X5l0bkk9QT76BHDao5PLK4a61yy094nI/view?usp=drive_open&usp=embed_facebook">Visitame app.sketch</a></strong></div></blockquote>
