### ISSUE TITLE
Unificar ayuda en navegación

### ISSUE THREAD

**Issue by uveybe** [Visitame/Design#5]
Deberíamos unificar la ayuda y navegación. Pongo algunos ejemplos:

--> aquí no tenemos ayuda. (y comentar que el botón de abajo redirigirá al inmueble no se repite el unlog que ya tenemos en la cabecera):
<img width="533" alt="captura de pantalla 2018-11-06 a las 12 49 56" src="https://user-images.githubusercontent.com/22731532/48062525-a00e5900-e1c2-11e8-8c7a-a6ac3b38dc5a.png">

--> aquí tenemos ayuda:
<img width="521" alt="captura de pantalla 2018-11-06 a las 12 49 49" src="https://user-images.githubusercontent.com/22731532/48062527-a00e5900-e1c2-11e8-845b-bb6e6604772a.png">

--> aquí no tenemos ayuda. igual deberíamos añadir el back en texto ¿el teléfono es incorrecto? Edítalo:
<img width="543" alt="captura de pantalla 2018-11-06 a las 12 49 44" src="https://user-images.githubusercontent.com/22731532/48062528-a00e5900-e1c2-11e8-80df-89c232fafa20.png">

**Comment by jimenacatalina** [comment]
0,5 horas
Lo dejo en sus correspondientes carpetas del Drive
