### ISSUE TITLE
Nuevo Logo de Ringo

### ISSUE THREAD

**Issue by uveybe** [Visitame/Design#6]
Necesitamos un nuevo logo de ringo para el site y documentos.

**Comment by jimenacatalina** [comment]
Dado que vamos a tomar la solución rápida de usar el logo de visitame.app y simplemente poner Ringo llevará 1 hora como mucho.

**Comment by jimenacatalina** [comment]
Dejo los logos en
https://drive.google.com/open?id=1k117-5pSIhE5zjq1Y_HRNu__LiwdZQYQ

Y las pantallas actualizadas en sus correspondientes carpetas

<blockquote><div><strong><a href="https://drive.google.com/open?id=1k117-5pSIhE5zjq1Y_HRNu__LiwdZQYQ">Meet Google Drive – One place for all your files</a></strong></div><div>Google Drive is a free way to keep your files backed up and easy to reach from any phone, tablet, or computer. Start with 15GB of Google storage – free.</div></blockquote>
