### ISSUE TITLE
Estructura de navegación de Backoffices de clientes v1

### ISSUE THREAD

**Issue by uveybe** [Visitame/Design#8]
Nuestros clientes, Sareb, van a tener acceso a herramientas y datos internos. Va a ser una parte core y hasta ahora no se había incorporado a un proceso de diseño, porque iban a ser solo herramientas internas. 

Sobre el modelo actual, podríamos plantear una navegación que permita el crecimiento, sea usable y tengo algo de marca por cliente.

Comentamos,

**Comment by jimenacatalina** [comment]
4 horas

**Comment by jimenacatalina** [comment]
Cambios sobre el modelo actual:
- Sustituir el isotipo de la casita por el logo de Ringo, que luego en cada cliente se podría personalizar a su propio logo.
- En la barra blanca de la cabecera se podrán poner accesos rápidos a algunas funcionalidades. Por ejemplo perfil de usuario, notificaciones, ayuda...
- En el menú lateral debe poderse agrupar secciones en desplegables, por si aumenta mucho el número de opciones y además para que su orden tenga algo de sentido. Solo hará falta icono para la denominación de grupo, no para cada opción.
- En el área de contenido la navegación por tabs, tablas, formularios y botones de acción deben estar dentro del módulo de fondo blanco.
- Los colores son los mismos que los de visitame.app, lo cual haría posible la personalización de color (si es que se quiere, no me parece fundamental en la herramienta interna)
- Unificar la tipografía a Nunito Sans, ahora hay un mix de Karla y Roboto
![estructura](https://user-images.githubusercontent.com/43912803/48697020-d2b54a00-ebe3-11e8-8795-d9afd4b5969d.png)

**Comment by jimenacatalina** [comment]
En Drive:
[https://drive.google.com/open?id=1HHhynePez7tz3_-mEoMSmWkowHhm-gQ_](https://drive.google.com/open?id=1HHhynePez7tz3_-mEoMSmWkowHhm-gQ_)
